name: demonstrate-secrets

on:
  workflow_dispatch
  
  jobs:
  getting-secrets:
    runs-on: ubuntu-latest
    steps: 
      - name: Get a secret and add to environment variables
        env: 
          MY_SECRET: ${{ secrets.MY_SECRET }}
        run: |
          echo "this is my secret $MY_SECRET"