name: demonstrate-secrets

on:
  workflow_dispatch

jobs:
  getting-secrets:
    runs-on: ubuntu-latest
    steps: 
      - name: Get a secret and add to environment variables
        env: 
          mysecret: ${{ secrets.MY_SECRET }} + "hi"
          foo: "bar"
        run: |
          echo "this is my secret $mysecret"
          echo "foo $bar"
      - name: Hello world
        run: echo Hello world $FIRST_NAME $middle_name $Last_Name!
        env:
          FIRST_NAME: Mona
          middle_name: The
          Last_Name: Octocat