name: test

on:
  workflow_dispatch
  
jobs:
  test:
    runs-on: ubuntu-latest

    steps: 
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with: 
        node-version: '12'
    - name: run a script
      run: echo running a script
    - name: setup node.js project
      run: npm ci
    - name: build node.js project
      run: npm run build
    - run: npm test > test-results.log
    - name: upload test results
      uses: actions/upload-artifact@v1
      with: 
        name: test-results
        path: test-results.log

            

