name: whatever

on:
  push:
    branches: [ master ]

jobs:
  whatever:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo whatever
